/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * REST API
 * REST API
 * OpenAPI spec version: 3.0.0
 */
export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityType = {
  ADMIN: 'ADMIN',
  AGENCY: 'AGENCY',
} as const

export interface Activity {
  userId: string
  operationId: string
  type: ActivityType
  parameters?: string
  variables?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface Agency {
  title: string
  description?: string
  email: string
  userId?: string
  walletAddress?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface CreateAgencyInput {
  title: string
  description?: string
  email: string
  walletAddress: string
}

export interface UpdateAgencyInput {
  title?: string
  description?: string
  walletAddress?: string
}

export interface Epoch {
  number: number
  startsAt: string
  endsAt?: string
  isEpochSnapshotProcessed?: boolean
  isTransactionsProcessed?: boolean
  isPayoutsProcessed?: boolean
  stakes?: string
  snapshotPayouts?: string
  inflationBonuses?: number
  totalStaked?: number
  excludedWalletsStakes?: string[]
  isPointsProcessed?: boolean
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface CreateEpochSnaphostProcessJobInput {
  epochNumber: number
}

export interface Job {
  scheduledAt: string
  isRecurring?: boolean
  type: JobType
  status: JobStatus
  parameters?: string
  defaultIntervalInMinutes?: number
  error?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobStatus = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  error: 'error',
} as const

export type JobType = (typeof JobType)[keyof typeof JobType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const JobType = {
  epochSnapshotProcess: 'epochSnapshotProcess',
  transactionsProcess: 'transactionsProcess',
  payoutsProcess: 'payoutsProcess',
} as const

export interface UpdateJobInput {
  scheduledAt?: string
  defaultIntervalInMinutes?: number
}

export interface BulkCreatePartnerItem {
  title: string
  walletAddress: string
  agencyId: string
  referralToken: string
  /**
   * @minimum 0
   * @maximum 100
   */
  bonusPercentage: number
  /**
   * @minimum 0
   * @maximum 100
   */
  agencyBonusPercentage: number
}

export interface BulkCreatePartnerInput {
  partners: BulkCreatePartnerItem[]
}

export interface CreatePartnerInput {
  title?: string
  walletAddress: string
  agencyId?: string
  referralToken?: string
  /**
   * @minimum 0
   * @maximum 100
   */
  bonusPercentage: number
  /**
   * @minimum 0
   * @maximum 100
   */
  agencyBonusPercentage?: number
}

export interface Partner {
  title?: string
  walletAddress: string
  profileId?: string
  agencyId?: string
  referralToken?: string
  bonusPercentage: number
  agencyBonusPercentage: number
  isUpgradedFromUser?: boolean
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface UpdatePartnerAgencyInput {
  agencyId: string
  /**
   * @minimum 0
   * @maximum 100
   */
  bonusPercentage?: number
  /**
   * @minimum 0
   * @maximum 100
   */
  agencyBonusPercentage?: number
}

export interface UpdatePartnerInput {
  title?: string
  referralToken?: string
}

export interface VerifyBulkCreatePartnersErrorItem {
  index?: number
  field?: string
  message?: string
}

export interface VerifyBulkCreatePartnersOutput {
  isPassed: boolean
  errors: VerifyBulkCreatePartnersErrorItem[]
}

export interface PayoutRequest {
  profileId: string
  partnerId?: string
  amountInLamports: number
  payoutIds: string[]
  status: PayoutRequestStatus
  transactionHash?: string
  processedAt?: string
  processedBy?: string
  note?: string
  walletAddress?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export type PayoutRequestStatus = (typeof PayoutRequestStatus)[keyof typeof PayoutRequestStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayoutRequestStatus = {
  pending: 'pending',
  completed: 'completed',
  rejected: 'rejected',
} as const

export interface ProcessPayoutRequestInput {
  isRejected: boolean
  note?: string
  transactionHash?: string
}

export interface Payout {
  walletAddress: string
  userRole: PayoutUserRole
  type: PayoutType
  status: PayoutStatus
  partnerId?: string
  agencyId?: string
  profileId?: string
  epochNumber: number
  amount: number
  referralStakeIds: string[]
  transactionHash?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export type PayoutStatus = (typeof PayoutStatus)[keyof typeof PayoutStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayoutStatus = {
  pending: 'pending',
  processed: 'processed',
} as const

export type PayoutType = (typeof PayoutType)[keyof typeof PayoutType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayoutType = {
  earnings: 'earnings',
  _points: ' points',
} as const

export type PayoutUserRole = (typeof PayoutUserRole)[keyof typeof PayoutUserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PayoutUserRole = {
  user: 'user',
  partner: 'partner',
  agency: 'agency',
  staker: 'staker',
} as const

export interface ProcessPayoutInput {
  transactionHash?: string
}

export interface ContactUsInput {
  reason?: string
  title: string
  message: string
}

export interface CreateProfileByReferralInput {
  walletAddress: string
  referralToken: string
}

export interface Profile {
  walletAddress: string
  invitedByWalletAddress?: string
  isPartner?: boolean
  referralToken?: string
  isAbleToCreatePayoutRequest?: boolean
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface ProfileStats {
  totalReferredStake?: number
  totalReferralEarnings?: number
  totalReferralPoints?: number
  epochEarnings?: number
  monthEarnings?: number
}

export interface UpdateProfilePartnerInput {
  partnerId: string
}

export interface UpgradeToPartnerInput {
  profileId: string
  title?: string
  agencyId?: string
  referralToken?: string
  /**
   * @minimum 0
   * @maximum 100
   */
  bonusPercentage: number
  /**
   * @minimum 0
   * @maximum 100
   */
  agencyBonusPercentage?: number
}

export interface ReferralConfig {
  referrerPointsPerSolanaEpoch: number
  referralPointsPerSolanaEpoch: number
  boostMultiplier: number
  payoutMinSolana: number
  calculateFrequencyInEpoch?: number
  maxPartnerPercentage: number
  title: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface UpdateReferralConfigInput {
  /** @minimum 0 */
  referrerPointsPerSolanaEpoch?: number
  /** @minimum 0 */
  referralPointsPerSolanaEpoch?: number
  /** @minimum 1 */
  boostMultiplier?: number
  /** @minimum 0 */
  payoutMinSolana?: number
  /** @minimum 0 */
  calculateFrequencyInEpoch?: number
  /**
   * @minimum 0
   * @maximum 100
   */
  maxPartnerPercentage?: number
}

export interface IndexMyStakesOutput {
  walletAddress: string
  reffererWalletAddress: string
  amount: number
  startEpoch: number
  endEpoch?: number
  isActive?: boolean
  validatorIdentifier?: string
  depositTransactionId: string
  withdrawalTransactionId?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface ReferralStake {
  walletAddress: string
  reffererWalletAddress: string
  amount: number
  startEpoch: number
  endEpoch?: number
  isActive?: boolean
  validatorIdentifier?: string
  depositTransactionId: string
  withdrawalTransactionId?: string
  partnerId?: string
  agencyId?: string
  profileId?: string
  partnerEarnings?: number
  agencyEarnings?: number
  pointsEarnings?: number
  stakerPointsEarnings?: number
  id?: string
  createdAt?: string
  updatedAt?: string
}

export interface AttemptCredentials {
  token: string
  code: string
}

export interface EmailCredentials {
  /** Email of the user to be used for authentication. */
  email: string
  /** Password of the user to be used for authentication. */
  password: string
  clientVersion?: number
}

export interface SessionToken {
  /** User auth session token. */
  token?: string
  /** Define is MFA enabled on user side and secon factor should be provided. */
  isMFARequired?: boolean
}

/**
 * Either (digest, signature, publicKey) for signMessage auth, or signedTransaction for Ledger-compatible transaction-based auth.
 */
export interface WalletCredentials {
  /** Challenge to be signed by user wallet (signMessage flow). */
  digest?: string
  /** Signature produced by user wallet for the signing challenge (base58 encoded). */
  signature?: string
  /** Public key (wallet address) of the user wallet (base58 encoded Solana public key). */
  publicKey?: string
  /** Base64-encoded signed memo transaction (Ledger-compatible). Use when signMessage fails (e.g. Phantom/Backpack/OKX with Ledger). Transaction is never broadcast - only verified off-chain. */
  signedTransaction?: string
}

export interface Transaction {
  walletAddress: string
  type: TransactionType
  amount: number
  epoch?: number
  validatorIdentifier?: string
  id?: string
  createdAt?: string
  updatedAt?: string
}

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
  deposit: 'deposit',
  withdrawal: 'withdrawal',
} as const

export interface InviteUserInput {
  email: string
  role: UserRole
}

export interface RegisterUserInput {
  password: string
  firstName?: string
  lastName?: string
  acceptedTermsAndPolicyVersion: number
  invitationToken: string
}

export interface RequestResetPasswordInput {
  /** Email of the user. */
  email: string
}

export interface ResetPasswordInput {
  /** Reset password token which user should recieve via email. */
  token: string
  /** New user password, to be set. */
  newPassword: string
}

export interface User {
  email: string
  isEmailVerified?: boolean
  lastAuthenticatedAt?: string
  isMFARequired?: boolean
  verificationEmailSentAt?: string
  role: UserRole
  invitedBy?: string
  id?: string
  createdAt?: string
  updatedAt?: string
  otpAuthProtocolURI?: string
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  ADMIN: 'ADMIN',
  AGENCY: 'AGENCY',
  OPERATOR: 'OPERATOR',
} as const

export type BulkCreatePartnerInputBody = BulkCreatePartnerInput

export type IndexActivitiesParams = {
  type?: string
  userId?: string
  operationId?: string
  sortOrder?: IndexActivitiesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexActivitiesSortOrder = (typeof IndexActivitiesSortOrder)[keyof typeof IndexActivitiesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexActivitiesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadActivityParams = {
  id: string
}

export type DeleteAgencyParams = {
  id: string
}

export type IndexAgenciesParams = {
  ids?: string[]
  title?: string
  userId?: string
  walletAddress?: string
  search?: string
  sortOrder?: IndexAgenciesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexAgenciesSortOrder = (typeof IndexAgenciesSortOrder)[keyof typeof IndexAgenciesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexAgenciesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadAgencyParams = {
  id: string
}

export type UpdateAgencyParams = {
  id: string
}

export type IndexEpochsParams = {
  ids?: string[]
  numbers?: number[]
  number?: string
  isEpochSnapshotProcessed?: string
  isTransactionsProcessed?: string
  isPayoutsProcessed?: string
  sortOrder?: IndexEpochsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexEpochsSortOrder = (typeof IndexEpochsSortOrder)[keyof typeof IndexEpochsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexEpochsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadEpochParams = {
  id: string
}

export type IndexJobsParams = {
  ids?: string[]
  isRecurring?: string
  type?: string
  status?: string
  sortOrder?: IndexJobsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexJobsSortOrder = (typeof IndexJobsSortOrder)[keyof typeof IndexJobsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexJobsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadJobParams = {
  id: string
}

export type UpdateJobParams = {
  id: string
}

export type DeletePartnerParams = {
  id: string
}

export type IndexPartnersParams = {
  ids?: string[]
  title?: string
  walletAddress?: string
  agencyId?: string
  search?: string
  sortOrder?: IndexPartnersSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexPartnersSortOrder = (typeof IndexPartnersSortOrder)[keyof typeof IndexPartnersSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexPartnersSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadPartnerParams = {
  id: string
}

export type UpdatePartnerParams = {
  id: string
}

export type UpdatePartnerAgencyParams = {
  id: string
}

export type IndexMyPayoutRequestsParams = {
  ids?: string
  status?: string
  transactionHash?: string
  sortOrder?: IndexMyPayoutRequestsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexMyPayoutRequestsSortOrder =
  (typeof IndexMyPayoutRequestsSortOrder)[keyof typeof IndexMyPayoutRequestsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexMyPayoutRequestsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type IndexPayoutRequestsParams = {
  ids?: string
  profileId?: string
  partnerId?: string
  status?: string
  transactionHash?: string
  processedBy?: string
  walletAddress?: string
  sortOrder?: IndexPayoutRequestsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexPayoutRequestsSortOrder =
  (typeof IndexPayoutRequestsSortOrder)[keyof typeof IndexPayoutRequestsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexPayoutRequestsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ProcessPayoutRequestParams = {
  id: string
}

export type ReadPayoutRequestParams = {
  id: string
}

export type IndexMyPayoutsParams = {
  ids?: string[]
  type?: string
  status?: string
  epochNumber?: string
  sortOrder?: IndexMyPayoutsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexMyPayoutsSortOrder = (typeof IndexMyPayoutsSortOrder)[keyof typeof IndexMyPayoutsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexMyPayoutsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type IndexPayoutsParams = {
  ids?: string[]
  walletAddress?: string
  userRole?: string
  type?: string
  status?: string
  partnerId?: string
  agencyId?: string
  profileId?: string
  epochNumber?: string
  sortOrder?: IndexPayoutsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexPayoutsSortOrder = (typeof IndexPayoutsSortOrder)[keyof typeof IndexPayoutsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexPayoutsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ProcessPayoutParams = {
  id: string
}

export type ReadPayoutParams = {
  id: string
}

export type IndexMyReferralProfilesParams = {
  ids?: string[]
  sortOrder?: IndexMyReferralProfilesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexMyReferralProfilesSortOrder =
  (typeof IndexMyReferralProfilesSortOrder)[keyof typeof IndexMyReferralProfilesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexMyReferralProfilesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type IndexProfilesParams = {
  ids?: string[]
  walletAddress?: string
  invitedByWalletAddress?: string
  isPartner?: string
  search?: string
  isReferralTokenPresent?: boolean
  sortOrder?: IndexProfilesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexProfilesSortOrder = (typeof IndexProfilesSortOrder)[keyof typeof IndexProfilesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexProfilesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadMyProfileStatsParams = {
  /**
   * The epoch number to get the epoch earnings for
   */
  epochNumber: number
}

export type ReadProfileParams = {
  id: string
}

export type UpdateProfilePartnerParams = {
  /**
   * Profile ID
   */
  id: string
}

export type IndexReferralConfigsParams = {
  ids?: string[]
  sortOrder?: IndexReferralConfigsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexReferralConfigsSortOrder =
  (typeof IndexReferralConfigsSortOrder)[keyof typeof IndexReferralConfigsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexReferralConfigsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadReferralConfigParams = {
  id: string
}

export type UpdateReferralConfigParams = {
  id: string
}

export type IndexMyReferralStakesParams = {
  walletAddress?: string
  startEpoch?: string
  endEpoch?: string
  isActive?: string
  validatorIdentifier?: string
  sortOrder?: IndexMyReferralStakesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexMyReferralStakesSortOrder =
  (typeof IndexMyReferralStakesSortOrder)[keyof typeof IndexMyReferralStakesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexMyReferralStakesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type IndexMyStakesParams = {
  sortOrder?: IndexMyStakesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexMyStakesSortOrder = (typeof IndexMyStakesSortOrder)[keyof typeof IndexMyStakesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexMyStakesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type IndexReferralStakesParams = {
  ids?: string[]
  walletAddress?: string
  reffererWalletAddress?: string
  startEpoch?: string
  endEpoch?: string
  isActive?: string
  validatorIdentifier?: string
  partnerId?: string
  agencyId?: string
  sortOrder?: IndexReferralStakesSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexReferralStakesSortOrder =
  (typeof IndexReferralStakesSortOrder)[keyof typeof IndexReferralStakesSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexReferralStakesSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadReferralStakeParams = {
  id: string
}

export type IndexTransactionsParams = {
  ids?: string[]
  walletAddress?: string
  type?: string
  amount?: string
  epoch?: string
  validatorIdentifier?: string
  sortOrder?: IndexTransactionsSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexTransactionsSortOrder = (typeof IndexTransactionsSortOrder)[keyof typeof IndexTransactionsSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexTransactionsSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadTransactionParams = {
  id: string
}

export type IndexUsersParams = {
  ids?: string[]
  email?: string
  role?: string
  search?: string
  sortOrder?: IndexUsersSortOrder
  /**
   * Field name to sort objects.
   */
  sortBy?: string
  /**
   * Should be used together with limit to implement pagination.
   */
  skip?: number
  /**
   * Should be used together with skip to implement pagination.
   */
  limit?: number
}

export type IndexUsersSortOrder = (typeof IndexUsersSortOrder)[keyof typeof IndexUsersSortOrder]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IndexUsersSortOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const

export type ReadUserParams = {
  id: string
}

export type ResendVerificationEmailParams = {
  /**
   * Email of registered user.
   */
  email: string
}

export type VerifyEmailParams = {
  /**
   * Verification token.
   */
  token: string
}
